context AiAgoraContext
    uint8[64] modelName
    double temperature
    int32 messagesLen
    uint8[16384] messagesBuffer
    EoAddress businessReplyAddr
    uint16[256] messageOffsets
    uint8 messageCount
    uint16 pendingReqSeq
